stable:
  impl: geth
  repo: ethereum/go-ethereum
  ref: master
  evm-bin: evm
develop:
  impl: geth
  repo: lightclient/go-ethereum
  ref: prague-devnet-0
  evm-bin: evm
eip7692:
  impl: evmone
  repo: ethereum/evmone
  ref: 6e85e661b175e52a007a8bcc4c2d0a855a81e425
  evm-bin: evmone-t8n